export const theme = {
  dark: {
    pageBackground: 'bg-black',
    text: 'text-gray-200',
    button: 'bg-blue-600',
    buttonText: 'text-white',
    avatarBorder: 'border-[#000000]',
    loadingBorder: '#F9F9F9',
    outline: 'outline-[#2E2E2E]',
    secondary: 'bg-[#151515]',
  },
  light: {
    pageBackground: 'bg-white',
    button: 'bg-blue-600',
    buttonText: 'text-white',
    text: 'text-black',
    avatarBorder: 'border-white',
    loadingBorder: '#F9F9F9',
    outline: 'outline-[#EBEBEB]',
    secondary: 'bg-[#FAFAFA]',
  },
  khaki: {
    pageBackground: 'bg-[#474B35]',
    text: 'text-[#C8DEBE]',
    button: 'bg-[#516B3C]',
    buttonText: 'text-white',
    avatarBorder: 'border-[#474B35]',
    loadingBorder: '#4C523C',
    outline: 'outline-[#4C523C]',
    secondary: 'bg-[#656A56]',
  },
  offwhite: {
    pageBackground: 'bg-white',
    button: 'bg-blue-600',
    buttonText: 'text-white',
    text: 'text-black',
    avatarBorder: 'border-white',
    loadingBorder: '#F9F9F9',
    outline: 'outline-[#EBEBEB]',
    secondary: 'bg-[#FAFAFA]',
  },
  ruby: {
    pageBackground: 'bg-black',
    backgroundImage:
      'https://qubicmedia.s3.ap-southeast-1.amazonaws.com/themes/ember/ember-bg.webp',
    text: 'text-white',
    avatarBorder: 'border-black',
    loadingBorder: '#250000',
    border: 'border-black',
    secondary: 'bg-red-600/70',
  },
};
