version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.13.1
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cp package.json build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build